version: '3.8'
services:
 postgres:
  image: postgres:latest
  volumes
  environment:
   POSTGRES_USER: user
   POSTGRES_PASSWORD: password
   POSTGRES_DB: mydb
  ports:
   - "5432:5432"
 backend:
 frontend: